// Data for the 6-person search page (index.html). See CLAUDE.md for schema & rules.
// Keep the object valid JSON. Bump "updated" after every change.
window.HOUSING_DATA = {
  "updated": "2026-07-13",
  "page": {
    "id": "six",
    "title": "London Housing — search for up to 6 people",
    "description": "4+ bedrooms (unequal sizes fine), 2+ bathrooms, furnished, ~30 min door-to-door to both Liverpool Street and Paddington (soft). Price guide £6,000–9,200 pcm total (soft — filter with the slider)."
  },
  "stations": [
    { "key": "liverpool_street", "name": "Liverpool Street", "label": "LivSt", "lat": 51.5178, "lng": -0.0823 },
    { "key": "paddington", "name": "Paddington", "label": "Padd", "lat": 51.5154, "lng": -0.1755 }
  ],
  "agents": [
    { "id": "kayandco", "name": "Kay & Co", "url": "https://www.kayandco.com/", "coverage": "Marylebone, Bayswater, Paddington", "status": "planned", "contacted": null, "note": "Dead centre of the target zone" },
    { "id": "sandfords", "name": "Sandfords", "url": "https://www.sandfords.com/", "coverage": "Marylebone, Regent's Park", "status": "planned", "contacted": null, "note": "" },
    { "id": "domusnova", "name": "Domus Nova", "url": "https://domusnova.com/london-lettings/", "coverage": "Notting Hill, Bayswater, W2", "status": "planned", "contacted": null, "note": "Design-led; two seed listings came from here" },
    { "id": "knightfrank", "name": "Knight Frank (Hyde Park)", "url": "https://www.knightfrank.co.uk/rent", "coverage": "Hyde Park, W2, Marylebone", "status": "planned", "contacted": null, "note": "" },
    { "id": "savills", "name": "Savills (Westminster / Islington)", "url": "https://search.savills.com/list/property-to-rent/london", "coverage": "Prime, city-wide", "status": "planned", "contacted": null, "note": "Several seed listings from here" },
    { "id": "hamptons", "name": "Hamptons (City / Maida Vale)", "url": "https://www.hamptons.co.uk/rent/", "coverage": "City fringe, W9, wide network", "status": "planned", "contacted": null, "note": "" },
    { "id": "chestertons", "name": "Chestertons (Islington / Notting Hill)", "url": "https://www.chestertons.co.uk/property-to-rent/", "coverage": "Islington, Notting Hill, Paddington", "status": "planned", "contacted": null, "note": "" },
    { "id": "marshparsons", "name": "Marsh & Parsons (Bayswater)", "url": "https://www.marshandparsons.co.uk/rent/", "coverage": "West & Central London", "status": "planned", "contacted": null, "note": "" },
    { "id": "dexters", "name": "Dexters (Paddington / Islington)", "url": "https://www.dexters.co.uk/property-lettings", "coverage": "Huge branch network", "status": "planned", "contacted": null, "note": "Big family-house stock" },
    { "id": "winkworth", "name": "Winkworth (Paddington / Bayswater)", "url": "https://www.winkworth.co.uk/rent", "coverage": "W2, W9, Islington", "status": "planned", "contacted": null, "note": "" },
    { "id": "davidastburys", "name": "David Astburys", "url": "https://davidastburys.com/", "coverage": "Islington", "status": "planned", "contacted": null, "note": "Dagmar Terrace seed via them" },
    { "id": "hotblack", "name": "Hotblack Desiato", "url": "https://www.hotblackdesiato.co.uk/", "coverage": "Islington, Highbury", "status": "planned", "contacted": null, "note": "" },
    { "id": "stirlingackroyd", "name": "Stirling Ackroyd", "url": "https://www.stirlingackroyd.com/", "coverage": "Shoreditch, Hackney, East", "status": "planned", "contacted": null, "note": "" },
    { "id": "capitalliving", "name": "Capital Living", "url": "https://www.capital-living.co.uk/", "coverage": "Professional group-shares, city-wide", "status": "planned", "contacted": null, "note": "Specialists in exactly this group size" }
  ],
  "options": [
    {
      "id": "dn-westbourne-terrace",
      "url": "https://domusnova.com/london-lettings/westbourne-terrace/",
      "source": "Domus Nova",
      "address": "Westbourne Terrace, Paddington",
      "area": "Bayswater / Paddington, W2",
      "lat": 51.5155, "lng": -0.1795, "approx_location": true,
      "price_pcm": 8667, "price_note": "£2,000 pw long let",
      "beds": 4, "baths": 4, "furnished": "unknown",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 25, "paddington": 5 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "4-bed/4-bath duplex (~2,166 sq ft) with private terrace, period detail, next to Paddington."
    },
    {
      "id": "dn-upper-montagu-street",
      "url": "https://domusnova.com/london-lettings/upper-montagu-street-2/",
      "source": "Domus Nova",
      "address": "Upper Montagu Street, Marylebone",
      "area": "Marylebone, W1H",
      "lat": 51.5197, "lng": -0.1610, "approx_location": true,
      "price_pcm": 8667, "price_note": "£2,000 pw long let; marked Let",
      "beds": 3, "baths": 2, "furnished": "unknown",
      "availability": "gone", "status": "promising",
      "commute_est": { "liverpool_street": 25, "paddington": 12 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "Retrouvius-designed 3-bed (~1,528 sq ft) with sky-lit dining hub and balcony. Now let."
    },
    {
      "id": "sv-220057",
      "url": "https://search.savills.com/property-detail/gbwprewsl220057l",
      "source": "Savills",
      "address": "Ashburnham Mews, Westminster",
      "area": "Westminster, SW1P 4FH",
      "lat": 51.4922, "lng": -0.1330, "approx_location": true,
      "price_pcm": 6250, "price_note": "",
      "beds": 3, "baths": 3, "furnished": "unknown",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 30, "paddington": 25 },
      "added": "2026-07-12", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "3-bed/3-bath flat/apartment in a Westminster mews. Confirmed available."
    },
    {
      "id": "sv-210001",
      "url": "https://search.savills.com/property-detail/gbwprewsl210001l",
      "source": "Savills",
      "address": "Vincent Square, Westminster",
      "area": "Westminster, SW1P 2NU",
      "lat": 51.4935, "lng": -0.1352, "approx_location": true,
      "price_pcm": 6500, "price_note": "",
      "beds": 3, "baths": 2, "furnished": "unknown",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 30, "paddington": 25 },
      "added": "2026-07-12", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "3-bed/2-bath flat/apartment overlooking Vincent Square. Confirmed available."
    },
    {
      "id": "sv-120102",
      "url": "https://search.savills.com/property-detail/gbwpreslf120102l",
      "source": "Savills",
      "address": "Pimlico (listing removed)",
      "area": "Pimlico, SW1V",
      "lat": 51.4890, "lng": -0.1355, "approx_location": true,
      "price_pcm": null, "price_note": "unknown",
      "beds": null, "baths": null, "furnished": "unknown",
      "availability": "gone", "status": "promising",
      "commute_est": { "liverpool_street": 35, "paddington": 25 },
      "added": "2026-07-12", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "Savills Pimlico listing — confirmed removed from the market."
    },
    {
      "id": "sv-170328",
      "url": "https://search.savills.com/property-detail/gbclellhl170328l",
      "source": "Savills",
      "address": "Bartholomew Close, Barbican",
      "area": "Farringdon / Barbican, EC1A 7BD",
      "lat": 51.5172, "lng": -0.0995, "approx_location": true,
      "price_pcm": 8750, "price_note": "New development; UNDER OFFER — could fall through",
      "beds": 3, "baths": 3, "furnished": "unknown",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 10, "paddington": 15 },
      "added": "2026-07-12", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "3-bed/3-bath new-development flat with large terrace by the Barbican; Farringdon Elizabeth line close."
    },
    {
      "id": "sv-170064",
      "url": "https://search.savills.com/property-detail/gbwprewsl170064l",
      "source": "Savills",
      "address": "Cambridge Street, Pimlico",
      "area": "Pimlico, SW1V 4QH",
      "lat": 51.4885, "lng": -0.1400, "approx_location": true,
      "price_pcm": 8000, "price_note": "Confirmed LET",
      "beds": 5, "baths": 3, "furnished": "unknown",
      "availability": "gone", "status": "promising",
      "commute_est": { "liverpool_street": 35, "paddington": 25 },
      "added": "2026-07-12", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "5-bed/3-bath house in Pimlico — rare bedroom count for the group. Now let."
    },
    {
      "id": "sv-120331",
      "url": "https://search.savills.com/property-detail/gbisreils120331l",
      "source": "Savills",
      "address": "Period house near Upper Street, Islington",
      "area": "Islington, N1",
      "lat": 51.5390, "lng": -0.1030, "approx_location": true,
      "price_pcm": null, "price_note": "no price on page; old listing, likely outdated",
      "beds": 3, "baths": 2, "furnished": "unknown",
      "availability": "unknown", "status": "promising",
      "commute_est": { "liverpool_street": 20, "paddington": 30 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": true,
      "summary": "3-bed period house over four floors near Angel and Highbury & Islington."
    },
    {
      "id": "otm-18665143",
      "url": "https://www.onthemarket.com/details/18665143/",
      "source": "OnTheMarket",
      "address": "Author, 180 York Way, King's Cross",
      "area": "King's Cross, N1C",
      "lat": 51.5420, "lng": -0.1230, "approx_location": true,
      "price_pcm": 7925, "price_note": "£1,829 pw",
      "beds": 3, "baths": 3, "furnished": "yes",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 20, "paddington": 20 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "3-bed/3-bath BTR flat (1,209 sq ft), 24h concierge, gym, pet-friendly; available now."
    },
    {
      "id": "otm-19592078",
      "url": "https://www.onthemarket.com/details/19592078/",
      "source": "OnTheMarket",
      "address": "The Courthouse, Horseferry Road, Westminster",
      "area": "Westminster, SW1P",
      "lat": 51.4948, "lng": -0.1290, "approx_location": true,
      "price_pcm": 6500, "price_note": "£1,500 pw; no longer on the market",
      "beds": 3, "baths": 3, "furnished": "yes",
      "availability": "gone", "status": "promising",
      "commute_est": { "liverpool_street": 30, "paddington": 25 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "5th-floor 3-bed/3-bath (~1,100 sq ft), two balconies, parking, concierge, gym. Gone."
    },
    {
      "id": "otm-19378456",
      "url": "https://www.onthemarket.com/details/19378456/",
      "source": "OnTheMarket",
      "address": "Romney House, Marsham Street, Westminster",
      "area": "Westminster, SW1P",
      "lat": 51.4953, "lng": -0.1287, "approx_location": true,
      "price_pcm": 6500, "price_note": "£1,500 pw; no longer on the market",
      "beds": 3, "baths": 3, "furnished": "part",
      "availability": "gone", "status": "promising",
      "commute_est": { "liverpool_street": 30, "paddington": 25 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "Modern 3-bed/3-bath in portered block with concierge, gym, parking. Gone."
    },
    {
      "id": "otm-16703047",
      "url": "https://www.onthemarket.com/details/16703047/",
      "source": "OnTheMarket",
      "address": "Great Portland Street, Fitzrovia",
      "area": "Fitzrovia, W1W",
      "lat": 51.5188, "lng": -0.1440, "approx_location": true,
      "price_pcm": 7500, "price_note": "£1,731 pw; SHORT LET only (2-month contract)",
      "beds": 3, "baths": 3, "furnished": "yes",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 20, "paddington": 15 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "3-bed/3-bath period flat (1,085 sq ft) between Marylebone and Fitzrovia. Short let only."
    },
    {
      "id": "otm-17298169",
      "url": "https://www.onthemarket.com/details/17298169/",
      "source": "OnTheMarket",
      "address": "Dagmar Terrace, Islington",
      "area": "Islington, N1",
      "lat": 51.5385, "lng": -0.1025, "approx_location": true,
      "price_pcm": 7500, "price_note": "£1,731 pw",
      "beds": 4, "baths": 3, "furnished": "no",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 20, "paddington": 30 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "Georgian end-of-terrace over five floors (1,765 sq ft), garden + terraces, near Angel. Unfurnished."
    },
    {
      "id": "otm-12326416",
      "url": "https://www.onthemarket.com/details/12326416/",
      "source": "OnTheMarket",
      "address": "Liberia Road, Highbury",
      "area": "Highbury, N5",
      "lat": 51.5487, "lng": -0.0955, "approx_location": true,
      "price_pcm": 6800, "price_note": "£1,569 pw; available 11 Jul 2026 — timing mismatch with mid-Sep",
      "beds": 4, "baths": 3, "furnished": "yes",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 20, "paddington": 35 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "3-storey period house (1,893 sq ft) with decked garden by Highbury Fields; furnished or unfurnished."
    },
    {
      "id": "otm-15233123",
      "url": "https://www.onthemarket.com/details/15233123/",
      "source": "OnTheMarket",
      "address": "15 Portman Square, Marylebone",
      "area": "Marylebone, W1H",
      "lat": 51.5157, "lng": -0.1560, "approx_location": true,
      "price_pcm": 7258, "price_note": "£1,675 pw; HMO licence in place — big plus for 6 sharers",
      "beds": 4, "baths": 3, "furnished": "yes",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 20, "paddington": 15 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "Refurbished lateral ground-floor flat (1,409 sq ft) in portered block on Portman Square; HMO licence in place."
    },
    {
      "id": "fx-nwhm5219414",
      "url": "https://www.foxtons.co.uk/properties-to-rent/w1t/nwhm5219414",
      "source": "Foxtons",
      "address": "Cleveland Street (101 on Cleveland), Fitzrovia",
      "area": "Fitzrovia, W1T",
      "lat": 51.5215, "lng": -0.1395, "approx_location": true,
      "price_pcm": 8000, "price_note": "£1,846 pw; Zero Deposit scheme",
      "beds": 3, "baths": 3, "furnished": "unknown",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 20, "paddington": 15 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "5th-floor 3-bed/3-bath (1,103 sq ft) in new development, 24h concierge, private outside space."
    },
    {
      "id": "otm-13381949",
      "url": "https://www.onthemarket.com/details/13381949/",
      "source": "OnTheMarket (Chestertons)",
      "address": "Delhi Street, King's Cross",
      "area": "King's Cross / Islington, N1",
      "lat": 51.5352, "lng": -0.1226, "approx_location": true,
      "price_pcm": 5300, "price_note": "£1,223 pw; 12-month min term; sharers welcome",
      "beds": 4, "baths": 3, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "liverpool_street": 20, "paddington": 20 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "available_from": "2026-07-14",
      "summary": "Refurbished 4-double-bed terrace over 3 floors near King's Cross; four en-suite shower rooms, patio garden."
    },
    {
      "id": "otm-19905342",
      "url": "https://www.onthemarket.com/details/19905342/",
      "source": "OnTheMarket (Hamptons)",
      "address": "Widegate Street, Spitalfields",
      "area": "Spitalfields, E1",
      "lat": 51.5178, "lng": -0.0782, "approx_location": true,
      "price_pcm": 6250, "price_note": "£1,442 pw",
      "beds": 4, "baths": 3, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "liverpool_street": 5, "paddington": 20 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "available_from": "2026-08-24",
      "summary": "Top-floor 4-double-bed apartment with roof terrace and acoustic glass, minutes' walk from Liverpool Street."
    },
    {
      "id": "otm-19911923",
      "url": "https://www.onthemarket.com/details/19911923/",
      "source": "OnTheMarket (OpenRent)",
      "address": "Canrobert Street, Bethnal Green",
      "area": "Bethnal Green, E2",
      "lat": 51.5286, "lng": -0.0603, "approx_location": true,
      "price_pcm": 6000, "price_note": "£1,385 pw; listing states max 4 tenants — would need negotiating for 6",
      "beds": 4, "baths": 4, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "liverpool_street": 15, "paddington": 30 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "available_from": "2026-09-15",
      "summary": "Victorian terrace with 4 en-suite bedrooms, open-plan living and garden; available exactly 15 Sep 2026."
    },
    {
      "id": "otm-19820987",
      "url": "https://www.onthemarket.com/details/19820987/",
      "source": "OnTheMarket (Messila Residential)",
      "address": "Fursecroft, Brown Street, Marylebone",
      "area": "Marylebone / Marble Arch, W1H",
      "lat": 51.5163, "lng": -0.1614, "approx_location": true,
      "price_pcm": 6067, "price_note": "£1,400 pw; agent flags 'highly suitable for 4 sharers'",
      "beds": 4, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "liverpool_street": 25, "paddington": 12 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "available_from": "2026-08-14",
      "summary": "Bright 1,380 sq ft 9th-floor apartment in portered mansion block near Marble Arch."
    },
    {
      "id": "otm-19000295",
      "url": "https://www.onthemarket.com/details/19000295/",
      "source": "OnTheMarket (Chestertons)",
      "address": "Queens Mews, Bayswater",
      "area": "Bayswater, W2",
      "lat": 51.5108, "lng": -0.1878, "approx_location": true,
      "price_pcm": 7750, "price_note": "£1,788 pw",
      "beds": 4, "baths": 3, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "liverpool_street": 30, "paddington": 12 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "available_from": "2026-08-17",
      "summary": "Renovated 1,756 sq ft period mews house with 4 beds, 3 baths and a study, short walk to Hyde Park."
    },
    {
      "id": "otm-19344962",
      "url": "https://www.onthemarket.com/details/19344962/",
      "source": "OnTheMarket (OpenRent)",
      "address": "St Stephen's Gardens, Westbourne Grove",
      "area": "Bayswater / Westbourne Grove, W2",
      "lat": 51.5175, "lng": -0.1955, "approx_location": true,
      "price_pcm": 8333, "price_note": "Bills included; £9,500 pcm all-bills quoted in description — clarify; states max 2 tenants — needs negotiating",
      "beds": 4, "baths": 3, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "liverpool_street": 30, "paddington": 15 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "available_from": "2026-08-12",
      "summary": "Spacious 3–4 bed duplex maisonette with two study spaces and garden access near Westbourne Grove."
    },
    {
      "id": "fx-chpk0155087",
      "url": "https://www.foxtons.co.uk/properties-to-rent/sw1p/chpk0155087",
      "source": "Foxtons",
      "address": "Carlisle Mansions, Westminster",
      "area": "Westminster / Victoria, SW1P",
      "lat": 51.4955, "lng": -0.1400, "approx_location": true,
      "price_pcm": 8251, "price_note": "£1,904 pw; 1,879 sq ft; Zero Deposit scheme",
      "beds": 4, "baths": 3, "furnished": "unknown",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 30, "paddington": 25 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "4-bed/3-bath mansion-block flat (1,879 sq ft) near Victoria."
    },
    {
      "id": "sv-250097",
      "url": "https://search.savills.com/property-detail/gbhaclvpr250097l",
      "source": "Savills",
      "address": "Unknown (Savills page needs browser check)",
      "area": "Unknown",
      "lat": null, "lng": null, "approx_location": false,
      "price_pcm": null, "price_note": "unknown",
      "beds": null, "baths": null, "furnished": "unknown",
      "availability": "unknown", "status": "promising",
      "commute_est": null,
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": true,
      "summary": "Savills listing (2025 vintage) — page is client-rendered; metadata pending a browser-based check."
    },
    {
      "id": "zp-73659735",
      "url": "https://www.zoopla.co.uk/to-rent/details/73659735/",
      "source": "Zoopla (UK Sotheby's)",
      "address": "Catherine Place, Westminster",
      "area": "Westminster / St James's, SW1E",
      "lat": 51.4985, "lng": -0.1400, "approx_location": true,
      "price_pcm": 9997, "price_note": "£2,307 pw; added 8 Jul 2026",
      "beds": 4, "baths": 3, "furnished": "yes",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 30, "paddington": 25 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "Period townhouse over five floors (2,526 sq ft) with courtyard garden, by St James's Park."
    },
    {
      "id": "zp-73632620",
      "url": "https://www.zoopla.co.uk/to-rent/details/73632620/",
      "source": "Zoopla (Rickman Properties)",
      "address": "Princes Gate Mews, South Kensington",
      "area": "South Kensington, SW7",
      "lat": 51.4975, "lng": -0.1730, "approx_location": true,
      "price_pcm": 10000, "price_note": "£2,308 pw; furnished or unfurnished; available immediately",
      "beds": 4, "baths": 3, "furnished": "yes",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 30, "paddington": 20 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "Mews house (2,129 sq ft) with garage, terrace and 3 baths, short walk to South Ken/Knightsbridge."
    },
    {
      "id": "zp-73201384",
      "url": "https://www.zoopla.co.uk/to-rent/details/73201384/",
      "source": "Zoopla (Emoov)",
      "address": "Portman Mansions, Porter Street, Marylebone",
      "area": "Marylebone, W1U",
      "lat": 51.5205, "lng": -0.1580, "approx_location": true,
      "price_pcm": 8990, "price_note": "£2,075 pw; marketed for SHORT-TERM stays from 1 month — confirm long-term possible; reduced 20 May",
      "beds": 4, "baths": 3, "furnished": "unknown",
      "availability": "live", "status": "promising",
      "commute_est": { "liverpool_street": 20, "paddington": 12 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "4-double-bed + study mansion-block flat (1,593 sq ft) with patio on Chiltern Street; porter."
    }
  ]
};
