// Data for the 2-person search page (duo.html). See CLAUDE.md for schema & rules.
// Keep the object valid JSON. Bump "updated" after every change.
window.HOUSING_DATA = {
  "updated": "2026-07-18",
  "page": {
    "id": "duo",
    "title": "London Housing — 2-person search",
    "description": "2 bedrooms, weighted towards Paddington (roughly ≤25 min door-to-door; Wembley and similar are too far). Price guide £2,200–3,200 pcm total (soft — filter with the slider)."
  },
  "stations": [
    { "key": "paddington", "name": "Paddington", "label": "Padd", "lat": 51.5154, "lng": -0.1755 }
  ],
  "agents": [
    { "id": "chestertons", "name": "Chestertons (Paddington)", "url": "https://www.chestertons.co.uk/property-to-rent/", "coverage": "Paddington, Hyde Park", "status": "planned", "contacted": null, "note": "" },
    { "id": "kayandco", "name": "Kay & Co", "url": "https://www.kayandco.com/", "coverage": "Paddington, Bayswater, Marylebone", "status": "planned", "contacted": null, "note": "" },
    { "id": "winkworth", "name": "Winkworth (Paddington / Maida Vale)", "url": "https://www.winkworth.co.uk/rent", "coverage": "W2, W9", "status": "planned", "contacted": null, "note": "" },
    { "id": "dexters", "name": "Dexters (Paddington)", "url": "https://www.dexters.co.uk/property-lettings", "coverage": "W2 and network-wide", "status": "planned", "contacted": null, "note": "" },
    { "id": "foxtons", "name": "Foxtons (Paddington)", "url": "https://www.foxtons.co.uk/properties-to-rent/", "coverage": "W2 and network-wide", "status": "planned", "contacted": null, "note": "" },
    { "id": "marshparsons", "name": "Marsh & Parsons (Little Venice)", "url": "https://www.marshandparsons.co.uk/rent/", "coverage": "W9, W2, NW6", "status": "planned", "contacted": null, "note": "" },
    { "id": "hamptons", "name": "Hamptons (Maida Vale)", "url": "https://www.hamptons.co.uk/rent/", "coverage": "W9, NW6", "status": "planned", "contacted": null, "note": "" },
    { "id": "kfh", "name": "KFH (Queen's Park / West Hampstead)", "url": "https://www.kfh.co.uk/rent", "coverage": "NW6, NW10", "status": "planned", "contacted": null, "note": "" }
  ],
  "options": [
    {
      "id": "otm-19905748",
      "url": "https://www.onthemarket.com/details/19905748/",
      "source": "OnTheMarket (Hamptons)",
      "address": "Saltram Crescent, Maida Vale",
      "area": "Maida Vale / Queen's Park border, W9",
      "lat": 51.5310, "lng": -0.2060, "approx_location": true,
      "price_pcm": 2400, "price_note": "£554 pw",
      "beds": 2, "baths": 1, "furnished": "part",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 20 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "available_from": "2026-09-09",
      "summary": "Two-double-bed first-floor flat with separate kitchen — available 9 Sep, near-perfect timing."
    },
    {
      "id": "otm-17803875",
      "url": "https://www.onthemarket.com/details/17803875/",
      "source": "OnTheMarket (Chase Evans)",
      "address": "Clarendon Court, 33 Maida Vale",
      "area": "Maida Vale / Little Venice, W9",
      "lat": 51.5270, "lng": -0.1830, "approx_location": true,
      "price_pcm": 2925, "price_note": "£675 pw",
      "beds": 2, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 12 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "available_from": "2026-08-18",
      "summary": "Refurbished 759 sq ft mansion-block flat, 2 baths, balcony, concierge, 6 min walk to Warwick Avenue."
    },
    {
      "id": "otm-19438411",
      "url": "https://www.onthemarket.com/details/19438411/",
      "source": "OnTheMarket (Marsh & Parsons)",
      "address": "Harvist Road, Queen's Park",
      "area": "Queen's Park, NW6",
      "lat": 51.5310, "lng": -0.2130, "approx_location": true,
      "price_pcm": 2800, "price_note": "£646 pw; furnishing not stated — confirm with agent",
      "beds": 2, "baths": 1, "furnished": "unknown",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 18 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "Newly refurbished 871 sq ft period conversion moments from Queen's Park (Bakerloo direct to Paddington)."
    },
    {
      "id": "otm-19897236",
      "url": "https://www.onthemarket.com/details/19897236/",
      "source": "OnTheMarket (Marsh & Parsons)",
      "address": "Plympton Road, Brondesbury",
      "area": "Kilburn / Brondesbury, NW6",
      "lat": 51.5390, "lng": -0.1990, "approx_location": true,
      "price_pcm": 2600, "price_note": "£600 pw; furnishing not stated — confirm with agent; added <7 days ago",
      "beds": 2, "baths": 1, "furnished": "unknown",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 20 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "summary": "First-floor flat with two equal doubles and high-ceilinged open-plan kitchen/reception; Bakerloo walkable."
    },
    {
      "id": "otm-19176368",
      "url": "https://www.onthemarket.com/details/19176368/",
      "source": "OnTheMarket (Foundation Estates)",
      "address": "Gaydon House, Bourne Terrace",
      "area": "Little Venice / Royal Oak, W2",
      "lat": 51.5225, "lng": -0.1900, "approx_location": true,
      "price_pcm": 2200, "price_note": "£508 pw, recently reduced; furnished or unfurnished",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 8 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "available_from": "now",
      "summary": "Split-level 710 sq ft 8th-floor flat with balcony near Royal Oak — one stop from Paddington. Cheapest find."
    },
    {
      "id": "otm-19276329",
      "url": "https://www.onthemarket.com/details/19276329/",
      "source": "OnTheMarket (Hamptons)",
      "address": "Amberley Road, Maida Vale",
      "area": "Maida Vale / Little Venice, W9",
      "lat": 51.5235, "lng": -0.1935, "approx_location": true,
      "price_pcm": 3250, "price_note": "£750 pw ALL BILLS INCLUDED — but SHORT-TERM let only; stopgap unless agent agrees long-term",
      "beds": 2, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 10 },
      "added": "2026-07-12", "last_checked": "2026-07-12", "needs_check": false,
      "available_from": "now",
      "summary": "Duplex with two doubles, two shower rooms and private SE-facing terrace."
    },
    {
      "id": "otm-19857445",
      "url": "https://www.onthemarket.com/details/19857445/",
      "source": "OnTheMarket (Foxtons)",
      "address": "Randolph Avenue, Maida Vale",
      "area": "Maida Vale, W9",
      "lat": 51.5270, "lng": -0.1855, "approx_location": true,
      "price_pcm": 3500, "price_note": "SHORT TERM LET listed — confirm 12-month possible",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 12 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "842 sq ft period mansion flat with small terrace and communal gardens by Maida Vale tube."
    },
    {
      "id": "otm-1773167",
      "url": "https://www.onthemarket.com/details/1773167/",
      "source": "OnTheMarket (Westways)",
      "address": "Bravington Road, Maida Hill",
      "area": "Maida Hill / Queen's Park, W9",
      "lat": 51.5283, "lng": -0.1990, "approx_location": true,
      "price_pcm": 2200, "price_note": "",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 18 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "available_from": "2026-09-04",
      "summary": "First-floor 2-double-bed, open-plan kitchen/living, 5 min to Queen's Park (Bakerloo) — available 4 Sep."
    },
    {
      "id": "otm-19688598",
      "url": "https://www.onthemarket.com/details/19688598/",
      "source": "OnTheMarket (Marsh & Parsons)",
      "address": "Goldhawk Road, Shepherd's Bush",
      "area": "Shepherd's Bush, W12",
      "lat": 51.5028, "lng": -0.2265, "approx_location": true,
      "price_pcm": 3000, "price_note": "Furnished or unfurnished",
      "beds": 2, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 25 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "710 sq ft garden flat with 2 baths and two patios, near Goldhawk Road and Hammersmith tubes."
    },
    {
      "id": "otm-19682704",
      "url": "https://www.onthemarket.com/details/19682704/",
      "source": "OnTheMarket (Oaklands Estates)",
      "address": "Collingbourne Road, Shepherd's Bush",
      "area": "Shepherd's Bush, W12",
      "lat": 51.5075, "lng": -0.2335, "approx_location": true,
      "price_pcm": 2600, "price_note": "",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 25 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "available_from": "2026-08-02",
      "summary": "Newly refurbished 731 sq ft flat with private garden, 10 min to Shepherd's Bush Market tube and Westfield."
    },
    {
      "id": "otm-19911844",
      "url": "https://www.onthemarket.com/details/19911844/",
      "source": "OnTheMarket (KFH)",
      "address": "Brassey Road, West Hampstead",
      "area": "Kilburn / West Hampstead, NW6",
      "lat": 51.5468, "lng": -0.1990, "approx_location": true,
      "price_pcm": 2500, "price_note": "Heating + hot water included; furnished or unfurnished",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 25 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "available_from": "2026-07-18",
      "summary": "1st-floor flat with private SW-facing balcony, short walk to Thameslink/Overground/Jubilee."
    },
    {
      "id": "otm-19858960",
      "url": "https://www.onthemarket.com/details/19858960/",
      "source": "OnTheMarket (Garrison Estates)",
      "address": "Tennyson Road, Queen's Park",
      "area": "Queen's Park, NW6",
      "lat": 51.5352, "lng": -0.2043, "approx_location": true,
      "price_pcm": 2750, "price_note": "UNFURNISHED; no pets; available 9 Sep — perfect timing",
      "beds": 2, "baths": 1, "furnished": "no",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 18 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "available_from": "2026-09-09",
      "summary": "602 sq ft period-conversion garden flat on quiet street by Queen's Park tube."
    },
    {
      "id": "otm-19863028",
      "url": "https://www.onthemarket.com/details/19863028/",
      "source": "OnTheMarket (OpenRent)",
      "address": "Fernhead Road, Maida Hill",
      "area": "Maida Hill / Queen's Park, W9",
      "lat": 51.5290, "lng": -0.2005, "approx_location": true,
      "price_pcm": 2590, "price_note": "No agent fees; max 2 tenants; landlord flexible on start",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 18 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "available_from": "2026-07-19",
      "summary": "Owner-managed garden flat with new bathroom, 4 min to Queen's Park tube (Bakerloo zone 2)."
    },
    {
      "id": "otm-19901905",
      "url": "https://www.onthemarket.com/details/19901905/",
      "source": "OnTheMarket (OpenRent)",
      "address": "Harrow Road (canalside), North Kensington",
      "area": "North Kensington / Kensal, W10",
      "lat": 51.5245, "lng": -0.2065, "approx_location": true,
      "price_pcm": 2800, "price_note": "No agent fees; start 24 Aug OR 13 Sep 2026; broadband included until Mar 2027",
      "beds": 2, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 15 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "available_from": "2026-08-24",
      "summary": "Canalside 2-bed/2-bath with balcony on the Grand Union Canal, near Westbourne Park and Kensal Green."
    },
    {
      "id": "otm-19884526",
      "url": "https://www.onthemarket.com/details/19884526/",
      "source": "OnTheMarket (Hamptons)",
      "address": "Kilburn Lane, Queen's Park",
      "area": "Queen's Park / Kensal, W10",
      "lat": 51.5300, "lng": -0.2110, "approx_location": true,
      "price_pcm": 2250, "price_note": "New to market",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 20 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "available_from": "2026-09-04",
      "summary": "First-floor flat with large reception and two doubles between Queen's Park and Kensal Rise — available 4 Sep."
    },
    {
      "id": "or-2964880",
      "url": "https://www.openrent.co.uk/property-to-rent/london/2-bed-flat-westbourne-terrace-w2/2964880",
      "source": "OpenRent",
      "address": "Westbourne Terrace, Paddington",
      "area": "Paddington, W2",
      "lat": 51.5128, "lng": -0.1785, "approx_location": true,
      "price_pcm": 3500, "price_note": "£807.69 pw; max 4 tenants; EPC B",
      "beds": 2, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 5 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "available_from": "2026-09-01",
      "summary": "2-bed/2-bath furnished flat ~4 min walk from Paddington — available exactly 1 Sep 2026."
    },
    {
      "id": "or-2947042",
      "url": "https://www.openrent.co.uk/property-to-rent/london/2-bed-flat-gloucester-terrace-w2/2947042",
      "source": "OpenRent",
      "address": "Gloucester Terrace, Bayswater",
      "area": "Paddington / Bayswater, W2",
      "lat": 51.5157, "lng": -0.1832, "approx_location": true,
      "price_pcm": 2700, "price_note": "£600 pw; max 2 tenants; available 25 Jul — timing needs luck or early start",
      "beds": 2, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 8 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "available_from": "2026-07-25",
      "summary": "Top-floor 2-bed/2-bath (1 en-suite) in Grade II listed building, 5 min from Paddington."
    },
    {
      "id": "dx-279315",
      "url": "https://www.dexters.co.uk/property-for-rent/flat-to-rent-in-gloucester-terrace-london-w2/279315",
      "source": "Dexters",
      "address": "Gloucester Terrace, Paddington",
      "area": "Paddington, W2",
      "lat": 51.5182, "lng": -0.1875, "approx_location": true,
      "price_pcm": 3250, "price_note": "£750 pw",
      "beds": 2, "baths": 1, "furnished": "unknown",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 8 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "Bright recently redecorated first-floor 2-bed with high ceilings, near Royal Oak/Paddington."
    },
    {
      "id": "fx-nwhm6204857",
      "url": "https://www.foxtons.co.uk/properties-to-rent/w3/nwhm6204857",
      "source": "Foxtons",
      "address": "Creswick Road, Acton",
      "area": "Acton, W3",
      "lat": 51.5122, "lng": -0.2688, "approx_location": true,
      "price_pcm": 3000, "price_note": "£692 pw, reduced; Zero Deposit scheme",
      "beds": 2, "baths": 1, "furnished": "unknown",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 20 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "New boutique-development 2-bed (898 sq ft), 10 min walk to Acton Main Line (Elizabeth line)."
    },
    {
      "id": "fx-chpk4414314",
      "url": "https://www.foxtons.co.uk/properties-to-rent/w13/chpk4414314",
      "source": "Foxtons",
      "address": "Singapore Road, West Ealing",
      "area": "West Ealing, W13",
      "lat": 51.5095, "lng": -0.3208, "approx_location": true,
      "price_pcm": 2600, "price_note": "£600 pw; Zero Deposit scheme",
      "beds": 2, "baths": 2, "furnished": "unknown",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 18 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "New-build 3rd-floor 2-bed/2-bath (816 sq ft) with balcony, near West Ealing Elizabeth line."
    },
    {
      "id": "wk-mdv260030",
      "url": "https://www.winkworth.co.uk/properties/lettings/stuart-tower-105-maida-vale-london-w9/MDV260030",
      "source": "Winkworth",
      "address": "Stuart Tower, 105 Maida Vale",
      "area": "Maida Vale, W9",
      "lat": 51.5286, "lng": -0.1830, "approx_location": true,
      "price_pcm": 2400, "price_note": "£554 pw; unfurnished or part-furnished",
      "beds": 2, "baths": 1, "furnished": "part",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 12 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "13th-floor 2-bed with Little Venice views in purpose-built block, 3 lifts, 24h security; 0.4 mi to Warwick Avenue."
    },
    {
      "id": "hm-p322120",
      "url": "https://www.hamptons.co.uk/properties/21901176/lettings/P322120",
      "source": "Hamptons",
      "address": "Sussex Gardens, Paddington",
      "area": "Paddington, W2",
      "lat": 51.5152, "lng": -0.1705, "approx_location": true,
      "price_pcm": 2800, "price_note": "£646 pw",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 5 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "available_from": "2026-08",
      "summary": "Recently redecorated lower-ground 2-double-bed (700+ sq ft) with private patio, short walk to Paddington."
    },
    {
      "id": "kfh-p236961",
      "url": "https://www.kfh.co.uk/north-west-london/queens-park/flats-to-rent/p236961/",
      "source": "KFH",
      "address": "Albert Road, Queen's Park",
      "area": "Queen's Park, NW6",
      "lat": 51.5340, "lng": -0.2046, "approx_location": true,
      "price_pcm": 4900, "price_note": "£1,130 pw ALL BILLS INCLUDED but SHORT LET (min 3 months) and well above guide — flagged, not filtered",
      "beds": 2, "baths": 2, "furnished": "no",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 12 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "New-build 2-bed/2-bath opposite Queen's Park station, 24h concierge, balcony; short-let terms."
    },
    {
      "id": "mp-hmm230034",
      "url": "https://www.marshandparsons.co.uk/properties-to-rent/london/property/HMM230034/shirland-road/",
      "source": "Marsh & Parsons",
      "address": "Shirland Road, Maida Vale",
      "area": "Maida Vale, W9",
      "lat": 51.5286, "lng": -0.1975, "approx_location": true,
      "price_pcm": 3302, "price_note": "£762 pw",
      "beds": 2, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 15 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "Modern 2-bed/2-bath with private garden plus insulated garden studio/workspace, near Warwick Avenue."
    },
    {
      "id": "ql-ferrum-332",
      "url": "https://www.quintainliving.com/development/ferrum/fe1/332-ferrum",
      "source": "Quintain Living (BTR)",
      "address": "332 Ferrum, Wembley Park",
      "area": "Wembley Park, HA9",
      "lat": 51.5568, "lng": -0.2818, "approx_location": true,
      "price_pcm": 2923, "price_note": "Utilities + wifi included, no fees; sister units same day: £2,891 and £2,917 unfurnished",
      "beds": 2, "baths": null, "furnished": "yes",
      "availability": "live", "status": "rejected",
      "commute_est": { "paddington": 30 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "Furnished 69 sqm loft-style 2-bed in BTR building. Rejected: Wembley too far out."
    },
    {
      "id": "un-wembley-2bed",
      "url": "https://uncle.co.uk/wembley/two-bedroom/",
      "source": "Uncle (BTR)",
      "address": "Uncle Wembley, 3 Park Lane",
      "area": "Wembley, HA9",
      "lat": 51.5528, "lng": -0.3020, "approx_location": true,
      "price_pcm": 2250, "price_note": "Units from £2,250 (also £2,600); furnished or unfurnished",
      "beds": 2, "baths": null, "furnished": "part",
      "availability": "live", "status": "rejected",
      "commute_est": { "paddington": 25 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": false,
      "summary": "BTR 2-beds with en-suites, balconies, gym, coworking; near Wembley Central. Rejected: Wembley too far out."
    },
    {
      "id": "ch-lil020097",
      "url": "https://www.rightmove.co.uk/properties/88172457",
      "source": "Chestertons (via Rightmove)",
      "address": "Warwick Avenue, Little Venice",
      "area": "Little Venice, W9",
      "lat": 51.5233, "lng": -0.1830, "approx_location": true,
      "price_pcm": 8450, "price_note": "FAR above guide — included because price is never a hard filter; 1,400 sq ft; verify current price/availability",
      "beds": 2, "baths": 2, "furnished": "unknown",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 8 },
      "added": "2026-07-13", "last_checked": "2026-07-13", "needs_check": true,
      "summary": "1,400 sq ft 2-bed/2-bath with 42' private garden + communal gardens with tennis courts, prime Warwick Avenue."
    },
    {
      "id": "zp-73717523",
      "url": "https://www.zoopla.co.uk/to-rent/details/73717523/",
      "source": "Zoopla (Kravens)",
      "address": "Conduit Place, Paddington",
      "area": "Paddington, W2",
      "lat": 51.5165, "lng": -0.1770, "approx_location": true,
      "price_pcm": 2900, "price_note": "£669 pw; reduced 16 Jul; 2 reception rooms + balcony",
      "beds": 2, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 5 },
      "added": "2026-07-18", "last_checked": "2026-07-18", "needs_check": false,
      "available_from": "2026-08-05",
      "summary": "Furnished 2-bed/2-bath with two reception rooms and a balcony, moments from Paddington station."
    },
    {
      "id": "zp-73724057",
      "url": "https://www.zoopla.co.uk/to-rent/details/73724057/",
      "source": "Zoopla (Newington)",
      "address": "Cambridge Square, Paddington",
      "area": "Paddington, W2",
      "lat": 51.5165, "lng": -0.1710, "approx_location": true,
      "price_pcm": 3228, "price_note": "£745 pw; 2nd bedroom/study; lift, 24h concierge, communal gardens",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 5 },
      "added": "2026-07-18", "last_checked": "2026-07-18", "needs_check": false,
      "available_from": "2026-07-21",
      "summary": "Bright furnished flat with open-plan living, second bed/study and skyline views; lift + concierge, close to Paddington."
    },
    {
      "id": "zp-73715881",
      "url": "https://www.zoopla.co.uk/to-rent/details/73715881/",
      "source": "Zoopla (Dexters)",
      "address": "Southwick Street, Hyde Park Estate",
      "area": "Hyde Park Estate / Paddington, W2",
      "lat": 51.5155, "lng": -0.1690, "approx_location": true,
      "price_pcm": 2750, "price_note": "£635 pw; ground floor, portered block, communal gardens; furnishing to confirm",
      "beds": 2, "baths": 1, "furnished": "unknown",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 7 },
      "added": "2026-07-18", "last_checked": "2026-07-18", "needs_check": true,
      "summary": "Two-double-bed ground-floor flat in a portered block with communal gardens, short walk from Paddington and Lancaster Gate."
    },
    {
      "id": "zp-71191889",
      "url": "https://www.zoopla.co.uk/to-rent/details/71191889/",
      "source": "Zoopla (Kinleigh Folkard & Hayward)",
      "address": "Edgware Road, Bayswater",
      "area": "Paddington / Bayswater, W2",
      "lat": 51.5175, "lng": -0.1720, "approx_location": true,
      "price_pcm": 2800, "price_note": "£646 pw; heating & hot water included; 24h porter, lift",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 8 },
      "added": "2026-07-18", "last_checked": "2026-07-18", "needs_check": false,
      "available_from": "2026-09-03",
      "summary": "Furnished 2-double-bed (594 sq ft) in a portered building moments from Paddington and Edgware Road; bills-inclusive heat/HW."
    },
    {
      "id": "zp-73746951",
      "url": "https://www.zoopla.co.uk/to-rent/details/73746951/",
      "source": "Zoopla (Venice Properties)",
      "address": "Hall Place, Paddington",
      "area": "Paddington / Edgware Road, W2",
      "lat": 51.5205, "lng": -0.1690, "approx_location": true,
      "price_pcm": 2600, "price_note": "£600 pw; 60 sq m; balcony + lift",
      "beds": 2, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 10 },
      "added": "2026-07-18", "last_checked": "2026-07-18", "needs_check": false,
      "available_from": "2026-09-01",
      "summary": "Refurbished furnished 2-bed/2-bath (700 sq ft) with balcony, separate kitchen and lift, minutes from Edgware Road; available 1 Sep."
    },
    {
      "id": "zp-73732401",
      "url": "https://www.zoopla.co.uk/to-rent/details/73732401/",
      "source": "Zoopla (Dexters)",
      "address": "Porchester Square, Bayswater",
      "area": "Bayswater / Royal Oak, W2",
      "lat": 51.5175, "lng": -0.1885, "approx_location": true,
      "price_pcm": 3250, "price_note": "£750 pw; part-furnished; 2nd floor (lift), balcony, portered, communal gardens",
      "beds": 2, "baths": 1, "furnished": "part",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 10 },
      "added": "2026-07-18", "last_checked": "2026-07-18", "needs_check": false,
      "summary": "Two-double-bed apartment with open-plan kitchen/reception onto a balcony in a portered block; Royal Oak and Paddington close by."
    },
    {
      "id": "zp-73744882",
      "url": "https://www.zoopla.co.uk/to-rent/details/73744882/",
      "source": "Zoopla (Kinleigh Folkard & Hayward)",
      "address": "Maida Avenue, Little Venice",
      "area": "Little Venice / Bayswater, W2",
      "lat": 51.5218, "lng": -0.1795, "approx_location": true,
      "price_pcm": 3100, "price_note": "£715 pw; part-furnished; canalside mansion block, porter, communal garden",
      "beds": 2, "baths": 1, "furnished": "part",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 12 },
      "added": "2026-07-18", "last_checked": "2026-07-18", "needs_check": false,
      "available_from": "now",
      "summary": "Recently refurbished 763 sq ft flat overlooking the Regent's Canal in a prestigious Little Venice mansion block; Warwick Avenue nearby."
    },
    {
      "id": "zp-73721012",
      "url": "https://www.zoopla.co.uk/to-rent/details/73721012/",
      "source": "Zoopla (Foxtons)",
      "address": "The Colonnades, Westbourne Grove",
      "area": "Bayswater, W2",
      "lat": 51.5170, "lng": -0.1880, "approx_location": true,
      "price_pcm": 3300, "price_note": "£762 pw; duplex; en-suite + guest cloakroom; portered, opposite communal gardens",
      "beds": 2, "baths": 2, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 13 },
      "added": "2026-07-18", "last_checked": "2026-07-18", "needs_check": false,
      "summary": "Spacious 1,107 sq ft furnished duplex over two floors in a portered building by Queensway/Westbourne Grove; Paddington a short distance."
    },
    {
      "id": "zp-73747243",
      "url": "https://www.zoopla.co.uk/to-rent/details/73747243/",
      "source": "Zoopla (Foxtons)",
      "address": "Kensington Gardens Square, Bayswater",
      "area": "Bayswater, W2",
      "lat": 51.5150, "lng": -0.1905, "approx_location": true,
      "price_pcm": 3250, "price_note": "£750 pw; part-furnished; private patio + entrance, period conversion",
      "beds": 2, "baths": 2, "furnished": "part",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 13 },
      "added": "2026-07-18", "last_checked": "2026-07-18", "needs_check": false,
      "summary": "Lower-ground 2-bed/2-bath (799 sq ft) with private patio in a period conversion off Westbourne Grove; Bayswater tube close."
    },
    {
      "id": "zp-73737176",
      "url": "https://www.zoopla.co.uk/to-rent/details/73737176/",
      "source": "Zoopla (Foxtons)",
      "address": "St Stephen's Gardens, Notting Hill",
      "area": "Bayswater / Westbourne Park, W2",
      "lat": 51.5178, "lng": -0.1955, "approx_location": true,
      "price_pcm": 2817, "price_note": "£650 pw; private entrance + courtyard, communal gardens",
      "beds": 2, "baths": 1, "furnished": "yes",
      "availability": "live", "status": "inbox",
      "commute_est": { "paddington": 15 },
      "added": "2026-07-18", "last_checked": "2026-07-18", "needs_check": false,
      "summary": "High-spec lower-ground 2-bed (648 sq ft) with private entrance and courtyard near Westbourne Grove/Portobello; Royal Oak & Westbourne Park nearby."
    }
  ]
};
